### ISSUE TITLE
Generate key crash duplicate symbol '_secp256k1GoPanicError'  both import ethereum crypto and go-secp256k1

### ISSUE THREAD

**Issue by crossle** [filecoin-project/go-address#16]
If use 	"github.com/filecoin-project/go-crypto" generate key crash `duplicate symbol '_secp256k1GoPanicError' in:`

```
sk, _ := crypto.GenerateKey()
addr, _ := NewSecp256k1Address(crypto.PublicKey(sk))
```

**Comment by crossle** [comment]
If use "github.com/ethereum/go-ethereum/crypto" will  work well, should update the import use ethereum crypto library

**Comment by Stebalien** [comment]
Unfortunately, it appears that importing both that package and go-crypto at the same time is impossible. There's really no clean way around this (other than to perform a mass symbol rename in https://github.com/ipsn/go-secp256k1.

**Comment by crossle** [comment]
Yes, appears import both, i switch to github.com/ethereum/go-ethereum/crypto

**Comment by crossle** [comment]
We fix it use ethereum crypto package `"github.com/ethereum/go-ethereum/crypto"`
