### ISSUE TITLE
Enforce a padding scheme

### ISSUE THREAD

**Issue by arajasek** [filecoin-project/go-address#22]
Because we don't enforce a padding scheme, we have `f1xpbyy4tkdx5si2bgo37dubc2xwv6fum5tk57mid` and `f1xpbyy4tkdx5si2bgo37dubc2xwv6fum5tk57mia` "actually" being the same address.

This isn't the easiest thing to fix, since we currently operate with "no padding",  but the solution is probably to refuse to decode other padding schemes:

- decode string X to address A
- re-encode address A to string X'
- fail if X not equal to X'

**Comment by arajasek** [comment]
Better suggestions welcome

**Comment by Stebalien** [comment]
It looks like padding isn't the issue:

```go
package main

import (
	"bytes"
	"fmt"

	"encoding/base32"
)

const encodeStd = "abcdefghijklmnopqrstuvwxyz234567"

// AddressEncoding defines the base32 config used for address encoding and decoding.
var AddressEncoding = base32.NewEncoding(encodeStd)

func main() {
	a := "xpbyy4tkdx5si2bgo37dubc2xwv6fum5tk57mia="
	b := "xpbyy4tkdx5si2bgo37dubc2xwv6fum5tk57mid="
	x, err := AddressEncoding.DecodeString(a)
	if err != nil {
		panic(err)
	}
	y, err := AddressEncoding.DecodeString(b)
	if err != nil {
		panic(err)
	}
	fmt.Println(bytes.Equal(x, y))
}
```

(prints true)
