### ISSUE TITLE
Structure fields need to be exposed to the public

### ISSUE THREAD

**Issue by beatlec** [filecoin-project/go-address#38]
The path is https://github.com/filecoin-project/go-address/blob/master/address.go, "type Address struct{ str string}"
  If the first letter is lowercase, it can only be used in this package. I need to use this structure in other packages, so it needs to be capitalized.
![bug](https://user-images.githubusercontent.com/53367946/212583319-6ad83031-677a-4130-bc23-87430a1adea9.png)

**Comment by Stebalien** [comment]
This field is intentionally private. Please call `.Bytes()` or `.String()`.

**Comment by beatlec** [comment]
> This field is intentionally private. Please call `.Bytes()` or `.String()`.

https://github.com/filecoin-project/go-fil-markets/blob/master/storagemarket/nodes.go 

![api](https://user-images.githubusercontent.com/53367946/212613558-96773c04-3b40-49be-8e00-e58125077191.png)

I want to call **SignProposal()**, if the structure is **not public**, how to pass in the **address** parameter ?

![how](https://user-images.githubusercontent.com/53367946/212613843-507ab25f-4589-4b7e-a749-ee476d8f55db.png)

Please give an example, thank you！
