### ISSUE TITLE
How to generate address offline

### ISSUE THREAD

**Issue by Wangmmx** [filecoin-project/go-address#5]
Hello, I would like to ask about the implementation method of specific address generation. I used the secp256k1 method to generate the pubKey. Afterwards, I want to generate the address myself. I saw the specific code here
https://github.com/filecoin-project/go-address/blob/8b6f2fb2b3efffb57f42d57f41532339e3938072/address.go#L201
but I don't understand why I got it wrong. Is it done again with a certain prefix encode? May I ask what calculation has been done from the pubkey to the final address? Thank you

**Comment by rllola** [comment]
Yeah the protocol should be one of those : https://filecoin-project.github.io/specs/#protocol-indicator

If you want to generate secp256k1 address the Protocol is SECP256K1 (https://github.com/filecoin-project/go-address/blob/master/address.go#L63).

So if I am not mistaken you should do a blake2-160 hash of your **uncompressed** (important!) public key and give that the payload arg.

See https://filecoin-project.github.io/specs/#protocol-1-libsecpk1-elliptic-curve-public-keys

**Comment by rllola** [comment]
You might want to take a look at this function https://github.com/filecoin-project/go-address/blob/master/address.go#L156
You seem to only have to give the pubkey and it will do the rest for you.

**Comment by Wangmmx** [comment]
Thank you very much! It helped a lot
